api_platform:
    version: 1.0.0
    title: 'Event Stream API'
    description: 'An API for publishing and subscribing to event streams.'
    show_webby: false
    path_segment_name_generator: 'EventStreamApi\PathSegmentGenerator'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            jwt:
                name: 'Authorization'
                type: 'header'
