framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        buses:
            event.bus:
                default_middleware: allow_no_handlers
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'Productively\Api\MessageHandler\Notification': async
