security:
    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - EventStreamApi\Security\GuardAuthenticator

    access_control:
        - { path: ^/api/docs., roles: PUBLIC_ACCESS }
        - { path: ^/api/contexts/, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: PUBLIC_ACCESS }