security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'

    providers:
        app_user_provider:
            id: jwt_auth.security.user.jwt_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            stateless: true
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - jwt_auth.security.guard.jwt_guard_authenticator

    access_control:
        - { path: ^/api/docs.json, roles: IS_AUTHENTICATED_ANONYMOUSLY } #temp
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY } #temp
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }