version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: eventstream-postgres
      working_dir: /application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=eventstream
      ports:
        - "8084:5432"
      command: ["postgres", "-c", "log_statement=all"]

    php-pm:
      build: docker/php-pm
      container_name: eventstream-ppm
      environment:
        - PHP_IDE_CONFIG=serverName=docker
        - APP_KERNEL_NAMESPACE=\EventStreamApi\
        - DATABASE_URL=postgresql://root:123@eventstream-postgres:5432/eventstream?serverVersion=11&charset=utf8
        - XDEBUG_MODE=debug
        - XDEBUG_CONFIG=discover_client_host=true start_with_request=yes
      volumes:
        - .:/application
      ports:
        - "8080:80"
