#index:
#    path: /
#    controller: App\Controller\DefaultController::index
root:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /api
    permanent: true